cluster_name="rancher"
base_domain = "dev.portal.onscale.com"
kubernetes_version = "1.25"
rancher_version = "2.7.3"
cert_manager_version = "1.12.1"
ingress_nginx_version = "4.6.0"
region = "us-east-1"
cert_manager_letsencrypt_email = "aws@onscale.com"